name: Energy Build and Package Windows

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  windows-64:
    runs-on: windows-2019
    env:
      LANG: zh_CN.UTF-8
      LC_ALL: zh_CN.UTF-8

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Config Base Environment
        run: |
          mkdir D:/app
          mkdir D:/app/install
          mkdir D:/app/install/amd64
        shell: bash

      - name: Install ENERGY CLI
        run: |
          cd D:/app
          git clone https://github.com/energye/energy.git
          cd energy/cmd/energy
          go install
          energy cli -v
        shell: bash

      - name: Install ENERGY CEF 109-64
        run: |
          cd D:/app
          energy install --all --cef=109
          energy env
        shell: bash

      - name: Build and Package AMD64
        run: |
          cd $RUNNER_WORKSPACE/wbxnkzdtjl
          
          energy build -o="漫客工具箱.exe"
          energy package -f="漫客工具箱.exe" -o="漫客工具箱.exe" -c
          
          mkdir -p build/windows/temp
          cp "build/windows/漫客工具箱.exe" build/windows/temp/
          
          powershell -Command "Compress-Archive -Path 'build/windows/temp/漫客工具箱.exe' -DestinationPath 'build/windows/temp/winamd64.zip' -Force"
          mv "build/windows/temp/winamd64.zip" "D:/app/install/amd64/"
        shell: bash

  windows-32:
    runs-on: windows-2019
    env:
      LANG: zh_CN.UTF-8
      LC_ALL: zh_CN.UTF-8

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Config Base Environment
        run: |
          mkdir D:/app
          mkdir D:/app/install
          mkdir D:/app/install/386
        shell: bash

      - name: Install ENERGY CLI
        run: |
          cd D:/app
          git clone https://github.com/energye/energy.git
          cd energy/cmd/energy
          go install
          energy cli -v
        shell: bash

      - name: Install ENERGY CEF 109-32
        run: |
          cd D:/app
          energy install --all --cef=109 --arch=386
          energy env
        shell: bash

      - name: Build and Package 32
        run: |
          cd $RUNNER_WORKSPACE/wbxnkzdtjl
          
          energy build -o="漫客工具箱.exe" --arch="386"
          energy package -f="漫客工具箱.exe" -o="漫客工具箱.exe" -c
          
          mkdir -p build/windows/temp
          cp "build/windows/漫客工具箱.exe" build/windows/temp/
          
          powershell -Command "Compress-Archive -Path 'build/windows/temp/漫客工具箱.exe' -DestinationPath 'build/windows/temp/win32.zip' -Force"
          mv "build/windows/temp/win32.zip" "D:/app/install/386/"
        shell: bash

  release:
    needs: [windows-64, windows-32]
    runs-on: windows-2019
    steps:
      - name: Check Install Directory
        run: |
          ls -al D:/app/install/
        shell: bash

      - name: Release Dynamic library
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: D:/app/install/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

