name: Energy Build and Package Windows

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  windows-64:
    runs-on: windows-2019
    env:
      LANG: zh_CN.UTF-8
      LC_ALL: zh_CN.UTF-8

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install NSIS
        run: |
          choco install nsis -y
        shell: powershell

      - name: Install NSIS Chinese Language Files
        run: |
          # 获取 NSIS 安装路径
          $NSIS_PATH = (Get-Command makensis).Source | Split-Path -Parent
          echo "NSIS Path: $NSIS_PATH"
          
          # 创建语言文件目录
          $LANG_PATH = Join-Path $NSIS_PATH "Contrib\Language files"
          mkdir -p "$LANG_PATH"
          
          # 下载中文语言文件
          curl -L -o "$LANG_PATH\chinese.nlf" "https://raw.githubusercontent.com/NSIS-Dev/NSIS/master/Contrib/Language%20files/chinese.nlf"
          curl -L -o "$LANG_PATH\chinese_simplified.nlf" "https://raw.githubusercontent.com/NSIS-Dev/NSIS/master/Contrib/Language%20files/chinese_simplified.nlf"
          
          # 验证文件是否下载成功
          echo "Language files in $LANG_PATH:"
          ls "$LANG_PATH"
        shell: powershell

      - name: Config Base Environment
        run: |
          mkdir -p D:/app/install/amd64
        shell: bash

      - name: Install ENERGY CLI
        run: |
          cd D:/app
          git clone https://github.com/energye/energy.git
          cd energy/cmd/energy
          go install
          energy cli -v
        shell: bash

      - name: Install ENERGY CEF 109-64
        run: |
          cd D:/app
          energy install --all --cef=109
          energy env
        shell: bash

      - name: Build and Package AMD64
        run: |
          cd $RUNNER_WORKSPACE/wbxnkzdtjl
          
          energy build -o="漫客工具箱.exe"
          energy package -f="漫客工具箱.exe" -o="漫客工具箱.exe" -c
          
          mkdir -p build/windows/temp
          cp "build/windows/漫客工具箱.exe" build/windows/temp/
          
          powershell -Command "Compress-Archive -Path 'build/windows/temp/漫客工具箱.exe' -DestinationPath 'build/windows/temp/winamd64.zip' -Force"
          mv "build/windows/temp/winamd64.zip" "D:/app/install/amd64/"
        shell: bash

      - name: Upload AMD64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-amd64-package
          path: D:/app/install/amd64/
          retention-days: 1

  windows-32:
    runs-on: windows-2019
    env:
      LANG: zh_CN.UTF-8
      LC_ALL: zh_CN.UTF-8

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install NSIS
        run: |
          choco install nsis -y
        shell: powershell

      - name: Install NSIS Chinese Language Files
        run: |
          # 获取 NSIS 安装路径
          $NSIS_PATH = (Get-Command makensis).Source | Split-Path -Parent
          echo "NSIS Path: $NSIS_PATH"
          
          # 创建语言文件目录
          $LANG_PATH = Join-Path $NSIS_PATH "Contrib\Language files"
          mkdir -p "$LANG_PATH"
          
          # 下载中文语言文件
          curl -L -o "$LANG_PATH\chinese.nlf" "https://raw.githubusercontent.com/NSIS-Dev/NSIS/master/Contrib/Language%20files/chinese.nlf"
          curl -L -o "$LANG_PATH\chinese_simplified.nlf" "https://raw.githubusercontent.com/NSIS-Dev/NSIS/master/Contrib/Language%20files/chinese_simplified.nlf"
          
          # 验证文件是否下载成功
          echo "Language files in $LANG_PATH:"
          ls "$LANG_PATH"
        shell: powershell

      - name: Config Base Environment
        run: |
          mkdir -p D:/app/install/386
        shell: bash

      - name: Install ENERGY CLI
        run: |
          cd D:/app
          git clone https://github.com/energye/energy.git
          cd energy/cmd/energy
          go install
          energy cli -v
        shell: bash

      - name: Install ENERGY CEF 109-32
        run: |
          cd D:/app
          energy install --all --cef=109 --arch=386
          energy env
        shell: bash

      - name: Build and Package 32
        run: |
          cd $RUNNER_WORKSPACE/wbxnkzdtjl
          
          energy build -o="漫客工具箱.exe" --arch="386"
          energy package -f="漫客工具箱.exe" -o="漫客工具箱.exe" -c
          
          mkdir -p build/windows/temp
          cp "build/windows/漫客工具箱.exe" build/windows/temp/
          
          powershell -Command "Compress-Archive -Path 'build/windows/temp/漫客工具箱.exe' -DestinationPath 'build/windows/temp/win32.zip' -Force"
          mv "build/windows/temp/win32.zip" "D:/app/install/386/"
        shell: bash

      - name: Upload 32-bit Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-32-package
          path: D:/app/install/386/
          retention-days: 1

  release:
    needs: [windows-64, windows-32]
    runs-on: windows-2019
    steps:
      - name: Download AMD64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: win-amd64-package
          path: D:/app/install/amd64

      - name: Download 32-bit Artifact
        uses: actions/download-artifact@v4
        with:
          name: win-32-package
          path: D:/app/install/386

      - name: Check Install Directory
        run: |
          ls -al D:/app/install/
        shell: bash

      - name: Release Dynamic library
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: D:/app/install/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

